lib/live_view_studio_web/router.ex
defmodule LiveViewStudioWeb.Router do
  use LiveViewStudioWeb, :router

  import LiveViewStudioWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {LiveViewStudioWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LiveViewStudioWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/light", LightLive
    live "/license", LicenseLive
    live "/sales-dashboard", SalesDashboardLive
    live "/search", SearchLive
    live "/autocomplete", AutocompleteLive
    live "/filter", FilterLive
    live "/servers", ServersLive
    live "/servers/new", ServersLive, :new
    live "/paginate", PaginateLive
    live "/sort", SortLive
    live "/volunteers", VolunteersLive
    live "/infinite-scroll", InfiniteScrollLive
    live "/sandbox", SandBoxLive
    live "/chart", ChartLive
    live "/map", MapLive
    live "/key-events", KeyEventsLive
    live "/desks", DesksLive
    live "/underwater", UnderwaterLive
    live "/underwater/show", UnderwaterLive, :show_modal
  end

  # Other scopes may use custom stacks.
  # scope "/api", LiveViewStudioWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LiveViewStudioWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    live "/users/register", UserRegistrationLive

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/topsecret", TopSecretLive

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/live_view_studio_web/controllers/page_controller.ex
defmodule LiveViewStudioWeb.PageController do
  use LiveViewStudioWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/live_view_studio_web/controllers/user_confirmation_controller.ex
defmodule LiveViewStudioWeb.UserConfirmationController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_confirmation_instructions(
        user,
        &Routes.user_confirmation_url(conn, :edit, &1)
      )
    end

    conn
    |> put_flash(
      :info,
      "If your email is in our system and it has not been confirmed yet, " <>
        "you will receive an email with instructions shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, %{"token" => token}) do
    render(conn, "edit.html", token: token)
  end

  # Do not log in the user after confirmation to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"token" => token}) do
    case Accounts.confirm_user(token) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "User confirmed successfully.")
        |> redirect(to: "/")

      :error ->
        # If there is a current user and the account was already confirmed,
        # then odds are that the confirmation link was already visited, either
        # by some automation or by the user themselves, so we redirect without
        # a warning message.
        case conn.assigns do
          %{current_user: %{confirmed_at: confirmed_at}} when not is_nil(confirmed_at) ->
            redirect(conn, to: "/")

          %{} ->
            conn
            |> put_flash(:error, "User confirmation link is invalid or it has expired.")
            |> redirect(to: "/")
        end
    end
  end
end

lib/live_view_studio_web/controllers/user_registration_controller.ex
defmodule LiveViewStudioWeb.UserRegistrationController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudio.Accounts.User
  alias LiveViewStudioWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/live_view_studio_web/controllers/user_reset_password_controller.ex
defmodule LiveViewStudioWeb.UserResetPasswordController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_user_password(conn.assigns.user))
  end

  # Do not log in the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Accounts.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/live_view_studio_web/controllers/user_session_controller.ex
defmodule LiveViewStudioWeb.UserSessionController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudioWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/live_view_studio_web/controllers/user_settings_controller.ex
defmodule LiveViewStudioWeb.UserSettingsController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudioWeb.UserAuth

  plug :assign_email_and_password_changesets

  def edit(conn, _params) do
    render(conn, "edit.html")
  end

  def update(conn, %{"action" => "update_email"} = params) do
    %{"current_password" => password, "user" => user_params} = params
    user = conn.assigns.current_user

    case Accounts.apply_user_email(user, password, user_params) do
      {:ok, applied_user} ->
        Accounts.deliver_update_email_instructions(
          applied_user,
          user.email,
          &Routes.user_settings_url(conn, :confirm_email, &1)
        )

        conn
        |> put_flash(
          :info,
          "A link to confirm your email change has been sent to the new address."
        )
        |> redirect(to: Routes.user_settings_path(conn, :edit))

      {:error, changeset} ->
        render(conn, "edit.html", email_changeset: changeset)
    end
  end

  def update(conn, %{"action" => "update_password"} = params) do
    %{"current_password" => password, "user" => user_params} = params
    user = conn.assigns.current_user

    case Accounts.update_user_password(user, password, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Password updated successfully.")
        |> put_session(:user_return_to, Routes.user_settings_path(conn, :edit))
        |> UserAuth.log_in_user(user)

      {:error, changeset} ->
        render(conn, "edit.html", password_changeset: changeset)
    end
  end

  def confirm_email(conn, %{"token" => token}) do
    case Accounts.update_user_email(conn.assigns.current_user, token) do
      :ok ->
        conn
        |> put_flash(:info, "Email changed successfully.")
        |> redirect(to: Routes.user_settings_path(conn, :edit))

      :error ->
        conn
        |> put_flash(:error, "Email change link is invalid or it has expired.")
        |> redirect(to: Routes.user_settings_path(conn, :edit))
    end
  end

  defp assign_email_and_password_changesets(conn, _opts) do
    user = conn.assigns.current_user

    conn
    |> assign(:email_changeset, Accounts.change_user_email(user))
    |> assign(:password_changeset, Accounts.change_user_password(user))
  end
end

lib/live_view_studio_web/live/autocomplete_live.ex
defmodule LiveViewStudioWeb.AutocompleteLive do
  use LiveViewStudioWeb, :live_view

  alias LiveViewStudio.{Stores, Cities}

  def mount(_params, _session, socket) do
    socket =
      assign(socket,
        zip: "",
        city: "",
        matches: [],
        stores: [],
        loading: false
      )

    {:ok, socket}
  end

  def render(assigns) do
    ~L"""
      <h1>Findo a Store</h1>
      <div id="search">

        <form phx-submit="zip-search">
          <input
            type="text"
            name="zip"
            value="<%= @zip %>"
            placeholder="Zip Code"
            autofocus
            autocomplete="off"
            <%= if @loading, do: "readonly" %>
          />
          <button type="submit">
            <img src="images/search.svg"/>
          </button>
        </form>

        <form phx-submit="city-search" phx-change="suggest-city">
          <input
            type="text"
            name="city"
            value="<%= @city %>"
            placeholder="City"
            autocomplete="off"
            list="matches"
            phx-debounce="1000"
            <%= if @loading, do: "readonly" %>
          />
          <button type="submit">
            <img src="images/search.svg"/>
          </button>
        </form>

        <datalist id="matches">
          <%= for match <- @matches do %>
            <option value="<%= match %>"><%= match %></option>
          <% end %>
        </datalist>

        <%= if @loading do %>
          <div class="loader">
            Loading...
          </div>
        <% end %>

        <div class="stores">
          <ul>
            <%= for store <- @stores do %>
              <li>
                <div class="first-line">
                  <div class="name">
                    <%= store.name %>
                  </div>
                  <div class="status">
                      <%= if store.open do %>
                        <span class="open">Open</span>
                      <% else %>
                        <span class="closed">Closed</span>
                      <% end %>
                  </div>
                </div>
                <div class="second-line">
                  <div class="street">
                    <img src="images/location.svg"/>
                    <%= store.street %>
                  </div>
                  <div class="phone_number">
                    <img src="images/phone.svg"/>
                    <%= store.phone_number %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    """
  end

  def handle_event("zip-search", %{"zip" => zip}, socket) do
    send(self(), {:run_zip_search, zip})

    socket =
      assign(socket,
        zip: zip,
        stores: [],
        loading: true
      )

    {:noreply, socket}
  end

  def handle_event("city-search", %{"city" => city}, socket) do
    send(self(), {:run_city_search, city})

    socket =
      assign(socket,
        city: city,
        stores: [],
        loading: true
      )

    {:noreply, socket}
  end

  def handle_event("suggest-city", %{"city" => prefix}, socket) do
    socket = assign(socket, matches: Cities.suggest(prefix))
    {:noreply, socket}
  end

  def handle_info({:run_zip_search, zip}, socket),
    do: seach_by(&Stores.search_by_zip/1, zip, socket)

  def handle_info({:run_city_search, city}, socket),
    do: seach_by(&Stores.search_by_city/1, city, socket)

  defp seach_by(serach_func, arg, socket) do
    case serach_func.(arg) do
      [] ->
        socket =
          socket
          |> put_flash(:info, "Not store matching \"#{arg}\"")
          |> assign(stores: [], loading: false)

        {:noreply, socket}

      stores ->
        socket = assign(socket, stores: stores, loading: false)
        {:noreply, socket}
    end
  end
end

lib/live_view_studio_web/live/chart_live.ex
defmodule LiveViewStudioWeb.ChartLive do
  use LiveViewStudioWeb, :live_view

  def mount(_params, _session, socket) do
    if connected?(socket) do
      :timer.send_interval(5000, self(), :update)
    end

    labels = 1..12 |> Enum.to_list()
    values = Enum.map(labels, fn _ -> get_reading() end)

    {:ok,
     assign(socket,
       chart_data: %{
         labels: labels,
         values: values
       },
       current_reading: List.last(labels)
     )}
  end

  def render(assigns) do
    ~L"""
    <div id="charting">
      <h1>Blood Sugar</h1>
      <div phx-update="ignore">
        <canvas id="chart-canvas"
                phx-hook="LineChart"
                data-chart-data="<%= Jason.encode!(@chart_data) %>"></canvas>
      </div>
      <div class="text-center">
        <button phx-click="get-reading">
          Get Reading
        </button>
        <div class="my-4">
          Total readings: <%= @current_reading %>
        </div>
      </div>
    </div>
    """
  end

  def handle_info(:update, socket) do
    {:noreply, add_point(socket)}
  end

  def handle_event("get-reading", _params, socket) do
    {:noreply, add_point(socket)}
  end

  defp add_point(socket) do
    socket = update(socket, :current_reading, &(&1 + 1))

    point = %{
      label: socket.assigns.current_reading,
      value: get_reading()
    }

    push_event(socket, "new-point", point)
  end

  defp get_reading, do: Enum.random(70..180)
end

lib/live_view_studio_web/live/components/creatures_component.ex
defmodule LiveViewStudioWeb.CreaturesComponent do
  use LiveViewStudioWeb, :live_component

  def render(assigns) do
    ~H"""
    <div>
      <h2><%= @title %></h2>
      <div class="creatures">
        🐙 🐳 🦑 🐡 🐚 🐋 🐟 🦈 🐠 🦀 🐬
      </div>

      <%= live_patch "I'm outta air!",
         to: @return_to, class: "button" %>
    </div>
    """
  end
end

lib/live_view_studio_web/live/components/header_component.ex
defmodule LiveViewStudioWeb.HeaderComponent do
  use LiveViewStudioWeb, :live_component

  def render(assigns) do
    ~L"""
    <h1 class="mb-2"><%= @title %></h1>
    <h2 class="text-center text-2xl text-gray-500 mb-8">
      <%= @subtitle %>
    </h2>
    """
  end
end

lib/live_view_studio_web/live/desks_live.html.heex
<h1>What's On Your Desk?</h1>
<div id="desks">
  <.form let={f} for={@changeset} url="#"
          phx_submit="save",
          phx_change="validate"
          id="create-desk"
        >
    <%= text_input f, :name, placeholder: "Name" %>
    <%= error_tag f, :name %>

    <div class="hint">
      Add up to <%= @uploads.photo.max_entries %> photos.
      (max <%= trunc(@uploads.photo.max_file_size/ 1_000_000) %> MB each)
    </div>

    <div class="drop" phx-drop-target={@uploads.photo.ref}>
      <%= live_file_input @uploads.photo %>
      or drag and drop here
    </div>

    <%= for {_ref, err} <- @uploads.photo.errors do %>
      <div class="error">
        <%= humanize(err) %>
      </div>
    <% end %>

    <%= for entry <- @uploads.photo.entries do %>
      <div class="entry">
        <%= live_img_preview entry %>
        <div class="progress">
          <div class="value">
            <%= entry.progress %>%
          </div>
          <div class="bar">
            <span style={"width: #{entry.progress}%"}></span>
          </div>
        </div>

        <a href="#" phx-click="cancel" phx-value-ref={entry.ref}>
          &times;
        </a>

        <%= for err <- upload_errors(@uploads.photo, entry) do %>
          <div class="error">
            <%= humanize(err) %>
          </div>
        <% end %>

      </div>
    <% end %>

    <%= submit "Upload", phx_disable_with: "Uploading..." %>
  </.form>

  <div id="photos" phx-update="prepend">
    <%= for desk <- @desks do %>
      <%= for {photo_url, index} <- Enum.with_index(desk.photo_urls)  do %>
        <div class="photo" id={"#{desk.id}-#{index}"}>
          <img src={photo_url}/>
          <div class="name">
            <%= desk.name %> (<%= index + 1 %>)
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

lib/live_view_studio_web/live/paginate_live.html.leex
<h1>Food Bank Donations</h1>
<div id="donations">
  <form phx-change="select-per-page">
    Show
    <select name="per-page">
      <%= options_for_select([5, 10, 15, 20], @options.per_page) %>
    </select>
    <label for="per-page">per page</label>
  </form>
  <div class="wrapper">
    <table>
        <thead>
        <tr>
            <th class="item">
            Item
            </th>
            <th>
            Quantity
            </th>
            <th>
            Days Until Expires
            </th>
        </tr>
        </thead>
        <tbody>
        <%= for donation <- @donations do %>
            <tr>
            <td class="item">
                <%= donation.emoji %> <%= donation.item %>
            </td>
            <td>
                <%= donation.quantity %> lbs
            </td>
            <td>
                <span class="<%= expires_class(donation) %>">
                <%= donation.days_until_expires %>
                </span>
            </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <div class="footer">
        <div class="pagination">
        <%= if @options.page > 1 do %>
            <%= pagination_link(@socket,
                                "Previous",
                                @options.page - 1,
                                @options.per_page,
                                "previous"
                                ) %>
        <% end %>

        <%= for i <- (@options.page - 2)..(@options.page + 2), i > 0 do %>
          <%= pagination_link(@socket,
                                i,
                                i,
                                @options.per_page,
                                (if i == @options.page, do: "active")
                                ) %>
        <% end %>
        <%= pagination_link(@socket,
                                "Next",
                                @options.page + 1,
                                @options.per_page,
                                "next"
                                ) %>
        </div>
    </div>
    </div>
</div>

lib/live_view_studio_web/live/sort_live.html.leex
<h1>Food Bank Donations</h1>
<div id="donations">
  <form phx-change="select-per-page">
    Show
    <select name="per-page">
      <%= options_for_select([5, 10, 15, 20], @options.per_page) %>
    </select>
    <label for="per-page">per page</label>
  </form>
  <div class="wrapper">
    <table>
        <thead>
        <tr>
            <th class="item">
                <%= sort_link(@socket, "Item", :item, @options) %>
            </th>
            <th>
                <%= sort_link(@socket, "Quantity", :quantity, @options) %>
            </th>
            <th>
                <%= sort_link(@socket, "Days Until Expires", :days_until_expires, @options) %>
            </th>
        </tr>
        </thead>
        <tbody>
        <%= for donation <- @donations do %>
            <tr>
            <td class="item">
                <%= donation.emoji %> <%= donation.item %>
            </td>
            <td>
                <%= donation.quantity %> lbs
            </td>
            <td>
                <span class="<%= expires_class(donation) %>">
                <%= donation.days_until_expires %>
                </span>
            </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <div class="footer">
        <div class="pagination">
        <%= if @options.page > 1 do %>
            <%= pagination_link(@socket,
                                "Previous",
                                @options.page - 1,
                                @options,
                                "previous"
                                ) %>
        <% end %>

        <%= for i <- (@options.page - 2)..(@options.page + 2), i > 0 do %>
          <%= pagination_link(@socket,
                                i,
                                i,
                                @options,
                                (if i == @options.page, do: "active")
                                ) %>
        <% end %>
        <%= pagination_link(@socket,
                                "Next",
                                @options.page + 1,
                                @options,
                                "next"
                                ) %>
        </div>
    </div>
    </div>
</div>

lib/live_view_studio_web/live/user_registration_live.html.heex
<h1>Live Register</h1>

<.form let={f} for={@changeset}
    action={Routes.user_registration_path(@socket, :create)}
    phx_submit="save"
    phx_change="validate"
    phx_trigger_action={@trigger_submit}>
  <%= label f, :email %>
  <%= email_input f, :email, required: true %>
  <%= error_tag f, :email %>

  <%= label f, :password %>
  <%= password_input f, :password, required: true, value: input_value(f, :password) %>
  <%= error_tag f, :password %>

  <div>
    <%= submit "Register", phx_disable_with: "Registering..." %>
  </div>
</.form>

<p>
  <%= link "Log in", to: Routes.user_session_path(@socket, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@socket, :new) %>
</p>

lib/live_view_studio_web/live/volunteers_live.html.leex
<%= live_component HeaderComponent,
  title: "Volunteer Check-In",
  subtitle: @recent_activity %>
<div id="checkin">
  <%= live_component VolunteerFormComponent, id: :new %>

  <div id="volunteers" phx-update="prepend">
    <%= for volunteer <- @volunteers do %>
    <%= live_component VolunteerComponent, id: volunteer.id ,volunteer: volunteer %>
    <% end %>
  </div>
</div>